# IMPORTANT:
# The time format is NOT in ticks anymore. 
# It's now in double format, which means it can store decimal numbers, of seconds. 
# ...
# HOW TO USE:
# "Age check delay": 
#       This is how often the plugin should check for 'old' mobs to kill.
#       Be cautious with this. Small changes...
# "Age limit": 
#       This is limit of age (in seconds) that a mob can have. 
#       Remember that their age is reset via a number of ways
# "Mob limit": 
#       How many mobs are allowed. 0 means no limit
# "Active radius": 
#       This is the radius (in blocks) around each player that is considered "inhabited".

Age_Check_Delay: 0.5
AgeLimit: 45
MobLimit: 50
Active_Radius: 50
Debug:
    onStartup: true
    showWhitelist: false
    onSpawn: false